warnings:
  classes:
    CartWidget:
      message: 'Widgets are no longer part of SS4'
    ShopAccountFormValidator:
      message: 'No longer needed in SS4, as it was only used to fix an issue in 3.x'
    DashboardRecentMembersPanel:
      message: 'removed'
    DashboardRecentOrdersChart:
      message: 'removed'
    DashboardRecentOrdersPanel:
      message: 'removed'
mappings:
  AccountPage: SilverShop\Core\Account\AccountPage
  AccountPage_Controller: SilverShop\Core\Account\AccountPageController
  OrderActionsForm: SilverShop\Core\Account\OrderActionsForm
  OrderActionsForm_Validator: SilverShop\Core\Account\OrderActionsFormValidator
  OrderManipulation: SilverShop\Core\Account\OrderManipulation
  ShopAccountForm: SilverShop\Core\Account\ShopAccountForm
  ShopMemberFactory: SilverShop\Core\Account\ShopMemberFactory
  RestrictionRegionCountryDropdownField: SilverShop\Core\Address\RestrictionRegionCountryDropdownField
  SetLocationForm: SilverShop\Core\Address\SetLocationForm
  LocationFormPageDecorator: SilverShop\Core\Address\LocationFormPageDecorator
  ZoneSelectField: SilverShop\Core\Address\ZoneSelectField
  CartEditField: SilverShop\Core\CartEditField
  CartForm: SilverShop\Core\Cart\CartForm
  CartPage: SilverShop\Core\Cart\CartPage
  CartPage_Controller: SilverShop\Core\Cart\CartPageController
  MatchObjectFilter: SilverShop\Core\Cart\MatchObjectFilter
  OrderTotalCalculator: SilverShop\Core\Cart\OrderTotalCalculator
  ShoppingCart: SilverShop\Core\Cart\ShoppingCart
  ShoppingCart_Controller: SilverShop\Core\Cart\ShoppingCartController
  ShopQuantityField: SilverShop\Core\Cart\ShopQuantityField
  DropdownShopQuantityField: SilverShop\Core\Cart\DropdownShopQuantityField
  ViewableCart: SilverShop\Core\Cart\ViewableCart
  Checkout: SilverShop\Core\Checkout\Checkout
  CheckoutComponentValidator: SilverShop\Core\Checkout\CheckoutComponentValidator
  CheckoutConfig: SilverShop\Core\Checkout\CheckoutConfig
  CheckoutFieldFactory: SilverShop\Core\Checkout\CheckoutFieldFactory
  CheckoutForm: SilverShop\Core\Checkout\CheckoutForm
  CheckoutPage: SilverShop\Core\Checkout\CheckoutPage
  CheckoutPage_Controller: SilverShop\Core\Checkout\CheckoutPageController
  AddressBookCheckoutComponent: SilverShop\Core\Checkout\Component\AddressBook
  ShippingAddressBookCheckoutComponent: SilverShop\Core\Checkout\Component\AddressBookShipping
  BillingAddressBookCheckoutComponent: SilverShop\Core\Checkout\Component\AddressBookBilling
  AddressCheckoutComponent: SilverShop\Core\Checkout\Component\Address
  ShippingAddressCheckoutComponent: SilverShop\Core\Checkout\Component\ShippingAddress
  BillingAddressCheckoutComponent: SilverShop\Core\Checkout\Component\BillingAddress
  CheckoutComponent: SilverShop\Core\Checkout\Component\CheckoutComponent
  CheckoutComponent_Namespaced: SilverShop\Core\Checkout\Component\CheckoutComponentNamespaced
  CheckoutComponentConfig: SilverShop\Core\Checkout\Component\CheckoutComponentConfig
  SinglePageCheckoutComponentConfig: SilverShop\Core\Checkout\Component\SinglePageCheckoutComponentConfig
  CustomerDetailsCheckoutComponent: SilverShop\Core\Checkout\Component\CustomerDetails
  MembershipCheckoutComponent: SilverShop\Core\Checkout\Component\Membership
  NotesCheckoutComponent: SilverShop\Core\Checkout\Component\Notes
  OnsitePaymentCheckoutComponent: SilverShop\Core\Checkout\Component\OnsitePayment
  PaymentCheckoutComponent: SilverShop\Core\Checkout\Component\Payment
  TermsCheckoutComponent: SilverShop\Core\Checkout\Component\Terms
  OrderEmailNotifier: SilverShop\Core\Checkout\OrderEmailNotifier
  OrderProcessor: SilverShop\Core\Checkout\OrderProcessor
  PaymentForm: SilverShop\Core\Checkout\PaymentForm
  CheckoutStep: SilverShop\Core\Checkout\Step\CheckoutStep
  CheckoutStep_Address: SilverShop\Core\Checkout\Step\Address
  CheckoutStep_AddressBook: SilverShop\Core\Checkout\Step\AddressBook
  CheckoutStep_ContactDetails: SilverShop\Core\Checkout\Step\ContactDetails
  CheckoutStep_Membership: SilverShop\Core\Checkout\Step\Membership
  CheckoutStep_PaymentMethod: SilverShop\Core\Checkout\Step\PaymentMethod
  CheckoutStep_Summary: SilverShop\Core\Checkout\Step\Summary
  SteppedCheckout: SilverShop\Core\Checkout\Step\SteppedCheckout
  OrdersAdmin: SilverShop\Core\Cms\OrdersAdmin
  OrderGridFieldDetailForm_ItemRequest: SilverShop\Core\Cms\OrderGridFieldDetailForm_ItemRequest
  ProductBulkLoader: SilverShop\Core\Cms\ProductBulkLoader
  ProductCatalogAdmin: SilverShop\Core\Cms\ProductCatalogAdmin
  ShopConfig: SilverShop\Core\Cms\ShopConfig
  ZoneAdmin: SilverShop\Core\Cms\ZoneAdmin
  ShopDevelopmentAdmin: SilverShop\Core\Dev\ShopDevelopmentAdmin
  Address: SilverShop\Core\Model\Address
  Buyable: SilverShop\Core\Model\Buyable
  CanBeFreeCurrency: SilverShop\Core\Model\FieldType\CanBeFreeCurrency
  I18nDatetime: SilverShop\Core\Model\FieldType\I18nDatetime
  ShopCountry: SilverShop\Core\Model\FieldType\ShopCountry
  ShopCurrency: SilverShop\Core\Model\FieldType\ShopCurrency
  MultiFieldPartialMatchFilter: SilverShop\Core\Model\Filter\MultiFieldPartialMatchFilter
  Order: SilverShop\Core\Model\Order
  OrderAttribute: SilverShop\Core\Model\OrderAttribute
  OrderItem: SilverShop\Core\Model\OrderItem
  OrderItemList: SilverShop\Core\Model\OrderItemList
  OrderModifier: SilverShop\Core\Model\OrderModifier
  OrderStatusLog: SilverShop\Core\Model\OrderStatusLog
  RegionRestriction: SilverShop\Core\Model\RegionRestriction
  ShopMember: SilverShop\Core\Model\ShopMember
  ShopPayment: SilverShop\Core\Model\ShopPayment
  ShopPaymentService: SilverShop\Core\Model\ShopPaymentService
  Zone: SilverShop\Core\Model\Zone
  ZoneRegion: SilverShop\Core\Model\ZoneRegion
  OrderModifierForm: SilverShop\Core\Modifiers\OrderModifierForm
  FreeShippingModifier: SilverShop\Core\Modifiers\Shipping\Free
  PickupShippingModifier: SilverShop\Core\Modifiers\Shipping\Pickup
  ShippingModifier: SilverShop\Core\Modifiers\Shipping\Base
  SimpleShippingModifier: SilverShop\Core\Modifiers\Shipping\Simple
  WeightShippingModifier: SilverShop\Core\Modifiers\Shipping\Weight
  SubTotalModifier: SilverShop\Core\Modifiers\SubTotal
  FlatTaxModifier: SilverShop\Core\Modifiers\Tax\FlatTax
  GlobalTaxModifier: SilverShop\Core\Modifiers\Tax\GlobalTax
  TaxModifier: SilverShop\Core\Modifiers\Tax\Base
  AddProductForm: SilverShop\Core\Product\AddProductForm
  Product: SilverShop\Core\Product\Product
  Product_Controller: SilverShop\Core\Product\ProductController
  Product_OrderItem: SilverShop\Core\Product\ProductOrderItem
  ProductCategory: SilverShop\Core\Product\ProductCategory
  ProductCategory_Controller: SilverShop\Core\Product\ProductCategoryController
  Product_Image: SilverShop\Core\Product\ProductImage
  ProductAttributeType: SilverShop\Core\Product\Variation\AttributeType
  ProductAttributeValue: SilverShop\Core\Product\Variation\AttributeValue
  ProductVariation: SilverShop\Core\Product\Variation\Variation
  ProductVariation_OrderItem: SilverShop\Core\Product\Variation\VariationOrderItem
  ProductVariationsExtension: SilverShop\Core\Product\Variation\ProductVariationsExtension
  VariationForm: SilverShop\Core\Product\Variation\VariationForm
  VariationFormValidator: SilverShop\Core\Product\Variation\VariationFormValidator
  AbandonedCartReport: SilverShop\Core\Reports\AbandonedCartReport
  CustomerReport: SilverShop\Core\Reports\CustomerReport
  ProductReport: SilverShop\Core\Reports\ProductReport
  ShopPeriodReport: SilverShop\Core\Reports\ShopPeriodReport
  ShopReport_Query: SilverShop\Core\Reports\ShopReportQuery
  ShopSalesReport: SilverShop\Core\Reports\ShopSalesReport
  ShopSideReport_FeaturedProducts: SilverShop\Core\Reports\SideReport\FeaturedProducts
  ShopSideReport_AllProducts: SilverShop\Core\Reports\SideReport\AllProducts
  ShopSideReport_NoImageProducts: SilverShop\Core\Reports\SideReport\NoImageProducts
  ShopSideReport_HeavyProducts: SilverShop\Core\Reports\SideReport\HeavyProducts
  TaxReport: SilverShop\Core\Reports\TaxReport
  ShopTools: SilverShop\Core\ShopTools
  ShopUserInfo: SilverShop\Core\ShopUserInfo
  CalculateProductPopularity: SilverShop\Core\Tasks\CalculateProductPopularity
  CartCleanupTask: SilverShop\Core\Tasks\CartCleanupTask
  CreateInternationalZoneTask: SilverShop\Core\Tasks\CreateInternationalZoneTask
  CustomersToGroupTask: SilverShop\Core\Tasks\CustomersToGroupTask
  PopulateCartTask: SilverShop\Core\Tasks\PopulateCartTask
  PopulateShopTask: SilverShop\Core\Tasks\PopulateShopTask
  ProductVariationsFromAttributeCombinations: SilverShop\Core\Tasks\ProductVariationsFromAttributeCombinations
  RecalculateAllOrdersTask: SilverShop\Core\Tasks\RecalculateAllOrdersTask
  ShopEmailPreviewTask: SilverShop\Core\Tasks\ShopEmailPreviewTask
  ShopMigrationTask: SilverShop\Core\Tasks\ShopMigrationTask
  AccountPageTest: SilverShop\Core\AccountPageTest
  OrderActionsFormTest: SilverShop\Core\OrderActionsFormTest
  MatchObjectFilterTest: SilverShop\Core\MatchObjectFilterTest
  ShoppingCartControllerTest: SilverShop\Core\ShoppingCartControllerTest
  ShoppingCartTest: SilverShop\Core\ShoppingCartTest
  ShoppingCartTest_TestShoppingCartHooksExtension: SilverShop\Core\ShoppingCartTest_TestShoppingCartHooksExtension
  ShoppingCartTest_TestShoppingCartErroringHooksExtension: SilverShop\Core\ShoppingCartTest_TestShoppingCartErroringHooksExtension
  AddressBookCheckoutComponentTest: SilverShop\Core\AddressBookCheckoutComponentTest
  CheckoutComponentTest: SilverShop\Core\CheckoutComponentTest
  CheckoutFormTest: SilverShop\Core\CheckoutFormTest
  CheckoutPageTest: SilverShop\Core\CheckoutPageTest
  CheckoutTest: SilverShop\Core\CheckoutTest
  NestedCheckoutTest: SilverShop\Core\NestedCheckoutTest
  OrderProcessorTest: SilverShop\Core\OrderProcessorTest
  OrderProcessorTest_CustomOrderItem: SilverShop\Core\OrderProcessorTest_CustomOrderItem
  OrderProcessorTest_PlaceFailExtension: SilverShop\Core\OrderProcessorTest_PlaceFailExtension
  SteppedCheckoutTest: SilverShop\Core\SteppedCheckoutTest
  ProductBulkLoaderTest: SilverShop\Core\ProductBulkLoaderTest
  AddressTest: SilverShop\Core\AddressTest
  ExtendedTestAddress: SilverShop\Core\ExtendedTestAddress
  CanBeFreeCurrencyTest: SilverShop\Core\CanBeFreeCurrencyTest
  I18nDatetimeTest: SilverShop\Core\I18nDatetimeTest
  ShopCountryTest: SilverShop\Core\ShopCountryTest
  ShopCurrencyTest: SilverShop\Core\ShopCurrencyTest
  OrderNotificationTest: SilverShop\Core\OrderNotificationTest
  OrderStatusLogTest: SilverShop\Core\OrderStatusLogTest
  OrderTest: SilverShop\Core\OrderTest
  OrderTest_TestStatusChangeExtension: SilverShop\Core\OrderTest_TestStatusChangeExtension
  RegionRestrictionTest: SilverShop\Core\RegionRestrictionTest
  RegionRestriction_RateTest: SilverShop\Core\RegionRestriction_RateTest
  ShopMemberTest: SilverShop\Core\ShopMemberTest
  ShopPaymentTest: SilverShop\Core\ShopPaymentTest
  ZoneTest: SilverShop\Core\ZoneTest
  FlatTaxModifierTest: SilverShop\Core\FlatTaxModifierTest
  GlobalTaxModifierTest: SilverShop\Core\GlobalTaxModifierTest
  OrderModifierTest: SilverShop\Core\OrderModifierTest
  OrderModifierTest_TestModifier: SilverShop\Core\OrderModifierTest_TestModifier
  SimpleShippingModifierTest: SilverShop\Core\SimpleShippingModifierTest
  AddProductFormTest: SilverShop\Core\AddProductFormTest
  CustomProductTest: SilverShop\Core\CustomProductTest
  CustomProduct: SilverShop\Core\CustomProduct
  CustomProduct_OrderItem: SilverShop\Core\CustomProduct_OrderItem
  ProductCategoryTest: SilverShop\Core\ProductCategoryTest
  ProductImageTest: SilverShop\Core\ProductImageTest
  ProductOrderItemTest: SilverShop\Core\ProductOrderItemTest
  ProductTest: SilverShop\Core\ProductTest
  ProductTest_FractionalDiscountExtension: SilverShop\Core\ProductTest_FractionalDiscountExtension
  ProductVariationTest: SilverShop\Core\ProductVariationTest
  ProductVariationVersionTest: SilverShop\Core\ProductVariationVersionTest
  ShopReportTest: SilverShop\Core\ShopReportTest
  ShopTest: SilverShop\Core\ShopTest
  ShopTestControllerExtension: SilverShop\Core\ShopTestControllerExtension
  ShopToolsTest: SilverShop\Core\ShopToolsTest
  ShopUserInfoTest: SilverShop\Core\ShopUserInfoTest
  CartCleanupTaskTest: SilverShop\Core\CartCleanupTaskTest
  CartCleanupTaskTest_CartCleanupTaskFake: SilverShop\Core\CartCleanupTaskTest_CartCleanupTaskFake
  ViewableCartTest: SilverShop\Core\ViewableCartTest
