warnings:
  classes:
    CartWidget:
      message: 'Widgets are no longer part of SS4'
    ShopAccountFormValidator:
      message: 'No longer needed in SS4, as it was only used to fix an issue in 3.x'
    DashboardRecentMembersPanel:
      message: 'removed'
    DashboardRecentOrdersChart:
      message: 'removed'
    DashboardRecentOrdersPanel:
      message: 'removed'
mappings:
  AccountPage: SilverShop\Page\AccountPage
  AccountPage_Controller: SilverShop\Page\AccountPageController
  OrderActionsForm: SilverShop\Forms\OrderActionsForm
  OrderActionsForm_Validator: SilverShop\Forms\OrderActionsFormValidator
  OrderManipulation: SilverShop\Extension\OrderManipulationExtension
  ShopAccountForm: SilverShop\Forms\ShopAccountForm
  ShopMemberFactory: SilverShop\Checkout\ShopMemberFactory
  RestrictionRegionCountryDropdownField: SilverShop\Forms\RestrictionRegionCountryDropdownField
  SetLocationForm: SilverShop\Forms\SetLocationForm
  LocationFormPageDecorator: SilverShop\Extension\LocationFormPageExtension
  ZoneSelectField: SilverShop\Forms\ZoneSelectField
  CartEditField: SilverShop\Forms\CartEditField
  CartForm: SilverShop\Forms\CartForm
  CartPage: SilverShop\Page\CartPage
  CartPage_Controller: SilverShop\Page\CartPageController
  MatchObjectFilter: SilverShop\ORM\Filters\MatchObjectFilter
  OrderTotalCalculator: SilverShop\Cart\OrderTotalCalculator
  ShoppingCart: SilverShop\Cart\ShoppingCart
  ShoppingCart_Controller: SilverShop\Cart\ShoppingCartController
  ShopQuantityField: SilverShop\Forms\ShopQuantityField
  DropdownShopQuantityField: SilverShop\Forms\DropdownShopQuantityField
  ViewableCart: SilverShop\Extension\ViewableCartExtension
  Checkout: SilverShop\Checkout\Checkout
  CheckoutComponentValidator: SilverShop\Forms\CheckoutComponentValidator
  CheckoutConfig: SilverShop\Checkout\CheckoutConfig
  CheckoutFieldFactory: SilverShop\Checkout\CheckoutFieldFactory
  CheckoutForm: SilverShop\Forms\CheckoutForm
  CheckoutPage: SilverShop\Page\CheckoutPage
  CheckoutPage_Controller: SilverShop\Page\CheckoutPageController
  AddressBookCheckoutComponent: SilverShop\Checkout\Component\AddressBook
  ShippingAddressBookCheckoutComponent: SilverShop\Checkout\Component\AddressBookShipping
  BillingAddressBookCheckoutComponent: SilverShop\Checkout\Component\AddressBookBilling
  AddressCheckoutComponent: SilverShop\Checkout\Component\Address
  ShippingAddressCheckoutComponent: SilverShop\Checkout\Component\ShippingAddress
  BillingAddressCheckoutComponent: SilverShop\Checkout\Component\BillingAddress
  CheckoutComponent: SilverShop\Checkout\Component\CheckoutComponent
  CheckoutComponent_Namespaced: SilverShop\Checkout\Component\CheckoutComponentNamespaced
  CheckoutComponentConfig: SilverShop\Checkout\CheckoutComponentConfig
  SinglePageCheckoutComponentConfig: SilverShop\Checkout\SinglePageCheckoutComponentConfig
  CustomerDetailsCheckoutComponent: SilverShop\Checkout\Component\CustomerDetails
  MembershipCheckoutComponent: SilverShop\Checkout\Component\Membership
  NotesCheckoutComponent: SilverShop\Checkout\Component\Notes
  OnsitePaymentCheckoutComponent: SilverShop\Checkout\Component\OnsitePayment
  PaymentCheckoutComponent: SilverShop\Checkout\Component\Payment
  TermsCheckoutComponent: SilverShop\Checkout\Component\Terms
  OrderEmailNotifier: SilverShop\Checkout\OrderEmailNotifier
  OrderProcessor: SilverShop\Checkout\OrderProcessor
  PaymentForm: SilverShop\Forms\PaymentForm
  CheckoutStep: SilverShop\Checkout\Step\CheckoutStep
  CheckoutStep_Address: SilverShop\Checkout\Step\Address
  CheckoutStep_AddressBook: SilverShop\Checkout\Step\AddressBook
  CheckoutStep_ContactDetails: SilverShop\Checkout\Step\ContactDetails
  CheckoutStep_Membership: SilverShop\Checkout\Step\Membership
  CheckoutStep_PaymentMethod: SilverShop\Checkout\Step\PaymentMethod
  CheckoutStep_Summary: SilverShop\Checkout\Step\Summary
  SteppedCheckout: SilverShop\Checkout\Step\SteppedCheckout
  OrdersAdmin: SilverShop\Admin\OrdersAdmin
  OrderGridFieldDetailForm_ItemRequest: SilverShop\Forms\GridField\OrderGridFieldDetailForm_ItemRequest
  ProductBulkLoader: SilverShop\Admin\ProductBulkLoader
  ProductCatalogAdmin: SilverShop\Admin\ProductCatalogAdmin
  ShopConfig: SilverShop\Extension\ShopConfigExtension
  ZoneAdmin: SilverShop\Admin\ZoneAdmin
  ShopDevelopmentAdmin: SilverShop\Dev\ShopDevelopmentAdmin
  Address: SilverShop\Model\Address
  Buyable: SilverShop\Model\Buyable
  CanBeFreeCurrency: SilverShop\ORM\FieldType\CanBeFreeCurrency
  I18nDatetime: SilverShop\ORM\FieldType\I18nDatetime
  ShopCountry: SilverShop\ORM\FieldType\ShopCountry
  ShopCurrency: SilverShop\ORM\FieldType\ShopCurrency
  MultiFieldPartialMatchFilter: SilverShop\ORM\Filters\MultiFieldPartialMatchFilter
  Order: SilverShop\Model\Order
  OrderAttribute: SilverShop\Model\OrderAttribute
  OrderItem: SilverShop\Model\OrderItem
  OrderItemList: SilverShop\ORM\OrderItemList
  OrderModifier: SilverShop\Model\Modifiers\OrderModifier
  OrderStatusLog: SilverShop\Model\OrderStatusLog
  RegionRestriction: SilverShop\Model\RegionRestriction
  ShopMember: SilverShop\Extension\MemberExtension
  ShopPayment: SilverShop\Extension\PaymentExtension
  ShopPaymentService: SilverShop\Extension\PaymentServiceExtension
  Zone: SilverShop\Model\Zone
  ZoneRegion: SilverShop\Model\ZoneRegion
  OrderModifierForm: SilverShop\Forms\OrderModifierForm
  FreeShippingModifier: SilverShop\Model\Modifiers\Shipping\Free
  PickupShippingModifier: SilverShop\Model\Modifiers\Shipping\Pickup
  ShippingModifier: SilverShop\Model\Modifiers\Shipping\Base
  SimpleShippingModifier: SilverShop\Model\Modifiers\Shipping\Simple
  WeightShippingModifier: SilverShop\Model\Modifiers\Shipping\Weight
  SubTotalModifier: SilverShop\Model\Modifiers\SubTotal
  FlatTaxModifier: SilverShop\Model\Modifiers\Tax\FlatTax
  GlobalTaxModifier: SilverShop\Model\Modifiers\Tax\GlobalTax
  TaxModifier: SilverShop\Model\Modifiers\Tax\Base
  AddProductForm: SilverShop\Forms\AddProductForm
  Product: SilverShop\Page\Product
  Product_Controller: SilverShop\Page\ProductController
  Product_OrderItem: SilverShop\Model\Product\OrderItem
  ProductCategory: SilverShop\Page\ProductCategory
  ProductCategory_Controller: SilverShop\Page\ProductCategoryController
  Product_Image: SilverShop\Extension\ProductImageExtension
  ProductAttributeType: SilverShop\Model\Variation\AttributeType
  ProductAttributeValue: SilverShop\Model\Variation\AttributeValue
  ProductVariation: SilverShop\Model\Variation\Variation
  ProductVariation_OrderItem: SilverShop\Model\Variation\OrderItem
  ProductVariationsExtension: SilverShop\Extension\ProductVariationsExtension
  VariationForm: SilverShop\Forms\VariationForm
  VariationFormValidator: SilverShop\Forms\VariationFormValidator
  AbandonedCartReport: SilverShop\Reports\AbandonedCartReport
  CustomerReport: SilverShop\Reports\CustomerReport
  ProductReport: SilverShop\Reports\ProductReport
  ShopPeriodReport: SilverShop\Reports\ShopPeriodReport
  ShopReport_Query: SilverShop\Reports\ShopReportQuery
  ShopSalesReport: SilverShop\Reports\ShopSalesReport
  ShopSideReport_FeaturedProducts: SilverShop\Reports\SideReport\FeaturedProducts
  ShopSideReport_AllProducts: SilverShop\Reports\SideReport\AllProducts
  ShopSideReport_NoImageProducts: SilverShop\Reports\SideReport\NoImageProducts
  ShopSideReport_HeavyProducts: SilverShop\Reports\SideReport\HeavyProducts
  TaxReport: SilverShop\Reports\TaxReport
  ShopTools: SilverShop\ShopTools
  ShopUserInfo: SilverShop\ShopUserInfo
  CalculateProductPopularity: SilverShop\Tasks\CalculateProductPopularity
  CartCleanupTask: SilverShop\Tasks\CartCleanupTask
  CreateInternationalZoneTask: SilverShop\Tasks\CreateInternationalZoneTask
  CustomersToGroupTask: SilverShop\Tasks\CustomersToGroupTask
  PopulateCartTask: SilverShop\Tasks\PopulateCartTask
  PopulateShopTask: SilverShop\Tasks\PopulateShopTask
  ProductVariationsFromAttributeCombinations: SilverShop\Tasks\ProductVariationsFromAttributeCombinations
  RecalculateAllOrdersTask: SilverShop\Tasks\RecalculateAllOrdersTask
  ShopEmailPreviewTask: SilverShop\Tasks\ShopEmailPreviewTask
  ShopMigrationTask: SilverShop\Tasks\ShopMigrationTask
  AccountPageTest: SilverShop\AccountPageTest
  OrderActionsFormTest: SilverShop\OrderActionsFormTest
  MatchObjectFilterTest: SilverShop\MatchObjectFilterTest
  ShoppingCartControllerTest: SilverShop\ShoppingCartControllerTest
  ShoppingCartTest: SilverShop\ShoppingCartTest
  ShoppingCartTest_TestShoppingCartHooksExtension: SilverShop\ShoppingCartTest_TestShoppingCartHooksExtension
  ShoppingCartTest_TestShoppingCartErroringHooksExtension: SilverShop\ShoppingCartTest_TestShoppingCartErroringHooksExtension
  AddressBookCheckoutComponentTest: SilverShop\AddressBookCheckoutComponentTest
  CheckoutComponentTest: SilverShop\CheckoutComponentTest
  CheckoutFormTest: SilverShop\CheckoutFormTest
  CheckoutPageTest: SilverShop\CheckoutPageTest
  CheckoutTest: SilverShop\CheckoutTest
  NestedCheckoutTest: SilverShop\NestedCheckoutTest
  OrderProcessorTest: SilverShop\OrderProcessorTest
  OrderProcessorTest_CustomOrderItem: SilverShop\OrderProcessorTest_CustomOrderItem
  OrderProcessorTest_PlaceFailExtension: SilverShop\OrderProcessorTest_PlaceFailExtension
  SteppedCheckoutTest: SilverShop\SteppedCheckoutTest
  ProductBulkLoaderTest: SilverShop\ProductBulkLoaderTest
  AddressTest: SilverShop\AddressTest
  ExtendedTestAddress: SilverShop\ExtendedTestAddress
  CanBeFreeCurrencyTest: SilverShop\CanBeFreeCurrencyTest
  I18nDatetimeTest: SilverShop\I18nDatetimeTest
  ShopCountryTest: SilverShop\ShopCountryTest
  ShopCurrencyTest: SilverShop\ShopCurrencyTest
  OrderNotificationTest: SilverShop\OrderNotificationTest
  OrderStatusLogTest: SilverShop\OrderStatusLogTest
  OrderTest: SilverShop\OrderTest
  OrderTest_TestStatusChangeExtension: SilverShop\OrderTest_TestStatusChangeExtension
  RegionRestrictionTest: SilverShop\RegionRestrictionTest
  RegionRestriction_RateTest: SilverShop\RegionRestriction_RateTest
  ShopMemberTest: SilverShop\ShopMemberTest
  ShopPaymentTest: SilverShop\ShopPaymentTest
  ZoneTest: SilverShop\ZoneTest
  FlatTaxModifierTest: SilverShop\FlatTaxModifierTest
  GlobalTaxModifierTest: SilverShop\GlobalTaxModifierTest
  OrderModifierTest: SilverShop\OrderModifierTest
  OrderModifierTest_TestModifier: SilverShop\OrderModifierTest_TestModifier
  SimpleShippingModifierTest: SilverShop\SimpleShippingModifierTest
  AddProductFormTest: SilverShop\AddProductFormTest
  CustomProductTest: SilverShop\CustomProductTest
  CustomProduct: SilverShop\CustomProduct
  CustomProduct_OrderItem: SilverShop\CustomProduct_OrderItem
  ProductCategoryTest: SilverShop\ProductCategoryTest
  ProductImageTest: SilverShop\ProductImageTest
  ProductOrderItemTest: SilverShop\ProductOrderItemTest
  ProductTest: SilverShop\ProductTest
  ProductTest_FractionalDiscountExtension: SilverShop\ProductTest_FractionalDiscountExtension
  ProductVariationTest: SilverShop\ProductVariationTest
  ProductVariationVersionTest: SilverShop\ProductVariationVersionTest
  ShopReportTest: SilverShop\ShopReportTest
  ShopTest: SilverShop\ShopTest
  ShopTestControllerExtension: SilverShop\ShopTestControllerExtension
  ShopToolsTest: SilverShop\ShopToolsTest
  ShopUserInfoTest: SilverShop\ShopUserInfoTest
  CartCleanupTaskTest: SilverShop\CartCleanupTaskTest
  CartCleanupTaskTest_CartCleanupTaskFake: SilverShop\CartCleanupTaskTest_CartCleanupTaskFake
  ViewableCartTest: SilverShop\ViewableCartTest
