mappings:
  AccountPage: SilverShop\Core\AccountPage
  AccountPage_Controller: SilverShop\Core\AccountPage_Controller
  OrderActionsForm: SilverShop\Core\OrderActionsForm
  OrderActionsForm_Validator: SilverShop\Core\OrderActionsForm_Validator
  OrderManipulation: SilverShop\Core\OrderManipulation
  ShopAccountForm: SilverShop\Core\ShopAccountForm
  ShopAccountFormValidator: SilverShop\Core\ShopAccountFormValidator
  ShopMemberFactory: SilverShop\Core\ShopMemberFactory
  RestrictionRegionCountryDropdownField: SilverShop\Core\RestrictionRegionCountryDropdownField
  SetLocationForm: SilverShop\Core\SetLocationForm
  LocationFormPageDecorator: SilverShop\Core\LocationFormPageDecorator
  ZoneSelectField: SilverShop\Core\ZoneSelectField
  CartEditField: SilverShop\Core\CartEditField
  CartForm: SilverShop\Core\CartForm
  CartPage: SilverShop\Core\CartPage
  CartPage_Controller: SilverShop\Core\CartPage_Controller
  CartWidget: SilverShop\Core\CartWidget
  MatchObjectFilter: SilverShop\Core\MatchObjectFilter
  OrderTotalCalculator: SilverShop\Core\OrderTotalCalculator
  ShoppingCart: SilverShop\Core\ShoppingCart
  ShoppingCart_Controller: SilverShop\Core\ShoppingCart_Controller
  ShopQuantityField: SilverShop\Core\ShopQuantityField
  DropdownShopQuantityField: SilverShop\Core\DropdownShopQuantityField
  ViewableCart: SilverShop\Core\ViewableCart
  Checkout: SilverShop\Core\Checkout
  CheckoutComponentValidator: SilverShop\Core\CheckoutComponentValidator
  CheckoutConfig: SilverShop\Core\CheckoutConfig
  CheckoutFieldFactory: SilverShop\Core\CheckoutFieldFactory
  CheckoutForm: SilverShop\Core\CheckoutForm
  CheckoutPage: SilverShop\Core\CheckoutPage
  CheckoutPage_Controller: SilverShop\Core\CheckoutPage_Controller
  AddressBookCheckoutComponent: SilverShop\Core\AddressBookCheckoutComponent
  ShippingAddressBookCheckoutComponent: SilverShop\Core\ShippingAddressBookCheckoutComponent
  BillingAddressBookCheckoutComponent: SilverShop\Core\BillingAddressBookCheckoutComponent
  AddressCheckoutComponent: SilverShop\Core\AddressCheckoutComponent
  ShippingAddressCheckoutComponent: SilverShop\Core\ShippingAddressCheckoutComponent
  BillingAddressCheckoutComponent: SilverShop\Core\BillingAddressCheckoutComponent
  CheckoutComponent: SilverShop\Core\CheckoutComponent
  CheckoutComponent_Namespaced: SilverShop\Core\CheckoutComponent_Namespaced
  CheckoutComponentConfig: SilverShop\Core\CheckoutComponentConfig
  SinglePageCheckoutComponentConfig: SilverShop\Core\SinglePageCheckoutComponentConfig
  CustomerDetailsCheckoutComponent: SilverShop\Core\CustomerDetailsCheckoutComponent
  MembershipCheckoutComponent: SilverShop\Core\MembershipCheckoutComponent
  NotesCheckoutComponent: SilverShop\Core\NotesCheckoutComponent
  OnsitePaymentCheckoutComponent: SilverShop\Core\OnsitePaymentCheckoutComponent
  PaymentCheckoutComponent: SilverShop\Core\PaymentCheckoutComponent
  TermsCheckoutComponent: SilverShop\Core\TermsCheckoutComponent
  OrderEmailNotifier: SilverShop\Core\OrderEmailNotifier
  OrderProcessor: SilverShop\Core\OrderProcessor
  PaymentForm: SilverShop\Core\PaymentForm
  CheckoutStep: SilverShop\Core\CheckoutStep
  CheckoutStep_Address: SilverShop\Core\CheckoutStep_Address
  CheckoutStep_AddressBook: SilverShop\Core\CheckoutStep_AddressBook
  CheckoutStep_ContactDetails: SilverShop\Core\CheckoutStep_ContactDetails
  CheckoutStep_Membership: SilverShop\Core\CheckoutStep_Membership
  CheckoutStep_PaymentMethod: SilverShop\Core\CheckoutStep_PaymentMethod
  CheckoutStep_Summary: SilverShop\Core\CheckoutStep_Summary
  SteppedCheckout: SilverShop\Core\SteppedCheckout
  DashboardRecentMembersPanel: SilverShop\Core\DashboardRecentMembersPanel
  DashboardRecentOrdersChart: SilverShop\Core\DashboardRecentOrdersChart
  DashboardRecentOrdersPanel: SilverShop\Core\DashboardRecentOrdersPanel
  OrdersAdmin: SilverShop\Core\OrdersAdmin
  OrderGridFieldDetailForm_ItemRequest: SilverShop\Core\OrderGridFieldDetailForm_ItemRequest
  ProductBulkLoader: SilverShop\Core\ProductBulkLoader
  ProductCatalogAdmin: SilverShop\Core\ProductCatalogAdmin
  ShopConfig: SilverShop\Core\ShopConfig
  ZoneAdmin: SilverShop\Core\ZoneAdmin
  ShopDevelopmentAdmin: SilverShop\Core\ShopDevelopmentAdmin
  Address: SilverShop\Core\Address
  Buyable: SilverShop\Core\Buyable
  CanBeFreeCurrency: SilverShop\Core\CanBeFreeCurrency
  I18nDatetime: SilverShop\Core\I18nDatetime
  ShopCountry: SilverShop\Core\ShopCountry
  ShopCurrency: SilverShop\Core\ShopCurrency
  MultiFieldPartialMatchFilter: SilverShop\Core\MultiFieldPartialMatchFilter
  Order: SilverShop\Core\Order
  OrderAttribute: SilverShop\Core\OrderAttribute
  OrderItem: SilverShop\Core\OrderItem
  OrderItemList: SilverShop\Core\OrderItemList
  OrderModifier: SilverShop\Core\OrderModifier
  OrderStatusLog: SilverShop\Core\OrderStatusLog
  RegionRestriction: SilverShop\Core\RegionRestriction
  ShopMember: SilverShop\Core\ShopMember
  ShopPayment: SilverShop\Core\ShopPayment
  ShopPaymentService: SilverShop\Core\ShopPaymentService
  Zone: SilverShop\Core\Zone
  ZoneRegion: SilverShop\Core\ZoneRegion
  OrderModifierForm: SilverShop\Core\OrderModifierForm
  FreeShippingModifier: SilverShop\Core\FreeShippingModifier
  PickupShippingModifier: SilverShop\Core\PickupShippingModifier
  ShippingModifier: SilverShop\Core\ShippingModifier
  SimpleShippingModifier: SilverShop\Core\SimpleShippingModifier
  WeightShippingModifier: SilverShop\Core\WeightShippingModifier
  SubTotalModifier: SilverShop\Core\SubTotalModifier
  FlatTaxModifier: SilverShop\Core\FlatTaxModifier
  GlobalTaxModifier: SilverShop\Core\GlobalTaxModifier
  TaxModifier: SilverShop\Core\TaxModifier
  AddProductForm: SilverShop\Core\AddProductForm
  Product: SilverShop\Core\Product
  Product_Controller: SilverShop\Core\Product_Controller
  Product_OrderItem: SilverShop\Core\Product_OrderItem
  ProductCategory: SilverShop\Core\ProductCategory
  ProductCategory_Controller: SilverShop\Core\ProductCategory_Controller
  Product_Image: SilverShop\Core\Product_Image
  ProductAttributeType: SilverShop\Core\ProductAttributeType
  ProductAttributeValue: SilverShop\Core\ProductAttributeValue
  ProductVariation: SilverShop\Core\ProductVariation
  ProductVariation_OrderItem: SilverShop\Core\ProductVariation_OrderItem
  ProductVariationsExtension: SilverShop\Core\ProductVariationsExtension
  VariationForm: SilverShop\Core\VariationForm
  VariationFormValidator: SilverShop\Core\VariationFormValidator
  AbandonedCartReport: SilverShop\Core\AbandonedCartReport
  CustomerReport: SilverShop\Core\CustomerReport
  ProductReport: SilverShop\Core\ProductReport
  ShopPeriodReport: SilverShop\Core\ShopPeriodReport
  ShopReport_Query: SilverShop\Core\ShopReport_Query
  ShopSalesReport: SilverShop\Core\ShopSalesReport
  ShopSideReport_FeaturedProducts: SilverShop\Core\ShopSideReport_FeaturedProducts
  ShopSideReport_AllProducts: SilverShop\Core\ShopSideReport_AllProducts
  ShopSideReport_NoImageProducts: SilverShop\Core\ShopSideReport_NoImageProducts
  ShopSideReport_HeavyProducts: SilverShop\Core\ShopSideReport_HeavyProducts
  TaxReport: SilverShop\Core\TaxReport
  ShopTools: SilverShop\Core\ShopTools
  ShopUserInfo: SilverShop\Core\ShopUserInfo
  CalculateProductPopularity: SilverShop\Core\CalculateProductPopularity
  CartCleanupTask: SilverShop\Core\CartCleanupTask
  CreateInternationalZoneTask: SilverShop\Core\CreateInternationalZoneTask
  CustomersToGroupTask: SilverShop\Core\CustomersToGroupTask
  PopulateCartTask: SilverShop\Core\PopulateCartTask
  PopulateShopTask: SilverShop\Core\PopulateShopTask
  ProductVariationsFromAttributeCombinations: SilverShop\Core\ProductVariationsFromAttributeCombinations
  RecalculateAllOrdersTask: SilverShop\Core\RecalculateAllOrdersTask
  ShopEmailPreviewTask: SilverShop\Core\ShopEmailPreviewTask
  ShopMigrationTask: SilverShop\Core\ShopMigrationTask
  AccountPageTest: SilverShop\Core\AccountPageTest
  OrderActionsFormTest: SilverShop\Core\OrderActionsFormTest
  MatchObjectFilterTest: SilverShop\Core\MatchObjectFilterTest
  ShoppingCartControllerTest: SilverShop\Core\ShoppingCartControllerTest
  ShoppingCartTest: SilverShop\Core\ShoppingCartTest
  ShoppingCartTest_TestShoppingCartHooksExtension: SilverShop\Core\ShoppingCartTest_TestShoppingCartHooksExtension
  ShoppingCartTest_TestShoppingCartErroringHooksExtension: SilverShop\Core\ShoppingCartTest_TestShoppingCartErroringHooksExtension
  AddressBookCheckoutComponentTest: SilverShop\Core\AddressBookCheckoutComponentTest
  CheckoutComponentTest: SilverShop\Core\CheckoutComponentTest
  CheckoutFormTest: SilverShop\Core\CheckoutFormTest
  CheckoutPageTest: SilverShop\Core\CheckoutPageTest
  CheckoutTest: SilverShop\Core\CheckoutTest
  NestedCheckoutTest: SilverShop\Core\NestedCheckoutTest
  OrderProcessorTest: SilverShop\Core\OrderProcessorTest
  OrderProcessorTest_CustomOrderItem: SilverShop\Core\OrderProcessorTest_CustomOrderItem
  OrderProcessorTest_PlaceFailExtension: SilverShop\Core\OrderProcessorTest_PlaceFailExtension
  SteppedCheckoutTest: SilverShop\Core\SteppedCheckoutTest
  ProductBulkLoaderTest: SilverShop\Core\ProductBulkLoaderTest
  AddressTest: SilverShop\Core\AddressTest
  ExtendedTestAddress: SilverShop\Core\ExtendedTestAddress
  CanBeFreeCurrencyTest: SilverShop\Core\CanBeFreeCurrencyTest
  I18nDatetimeTest: SilverShop\Core\I18nDatetimeTest
  ShopCountryTest: SilverShop\Core\ShopCountryTest
  ShopCurrencyTest: SilverShop\Core\ShopCurrencyTest
  OrderNotificationTest: SilverShop\Core\OrderNotificationTest
  OrderStatusLogTest: SilverShop\Core\OrderStatusLogTest
  OrderTest: SilverShop\Core\OrderTest
  OrderTest_TestStatusChangeExtension: SilverShop\Core\OrderTest_TestStatusChangeExtension
  RegionRestrictionTest: SilverShop\Core\RegionRestrictionTest
  RegionRestriction_RateTest: SilverShop\Core\RegionRestriction_RateTest
  ShopMemberTest: SilverShop\Core\ShopMemberTest
  ShopPaymentTest: SilverShop\Core\ShopPaymentTest
  ZoneTest: SilverShop\Core\ZoneTest
  FlatTaxModifierTest: SilverShop\Core\FlatTaxModifierTest
  GlobalTaxModifierTest: SilverShop\Core\GlobalTaxModifierTest
  OrderModifierTest: SilverShop\Core\OrderModifierTest
  OrderModifierTest_TestModifier: SilverShop\Core\OrderModifierTest_TestModifier
  SimpleShippingModifierTest: SilverShop\Core\SimpleShippingModifierTest
  AddProductFormTest: SilverShop\Core\AddProductFormTest
  CustomProductTest: SilverShop\Core\CustomProductTest
  CustomProduct: SilverShop\Core\CustomProduct
  CustomProduct_OrderItem: SilverShop\Core\CustomProduct_OrderItem
  ProductCategoryTest: SilverShop\Core\ProductCategoryTest
  ProductImageTest: SilverShop\Core\ProductImageTest
  ProductOrderItemTest: SilverShop\Core\ProductOrderItemTest
  ProductTest: SilverShop\Core\ProductTest
  ProductTest_FractionalDiscountExtension: SilverShop\Core\ProductTest_FractionalDiscountExtension
  ProductVariationTest: SilverShop\Core\ProductVariationTest
  ProductVariationVersionTest: SilverShop\Core\ProductVariationVersionTest
  ShopReportTest: SilverShop\Core\ShopReportTest
  ShopTest: SilverShop\Core\ShopTest
  ShopTestControllerExtension: SilverShop\Core\ShopTestControllerExtension
  ShopToolsTest: SilverShop\Core\ShopToolsTest
  ShopUserInfoTest: SilverShop\Core\ShopUserInfoTest
  CartCleanupTaskTest: SilverShop\Core\CartCleanupTaskTest
  CartCleanupTaskTest_CartCleanupTaskFake: SilverShop\Core\CartCleanupTaskTest_CartCleanupTaskFake
  ViewableCartTest: SilverShop\Core\ViewableCartTest
